### PR TITLE
Bump to LTS 18 and adds support for Aeson 2

### LINKED ISSUE #40: fails to build with aeson-2.0
```
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:147:30: error:
datadog                   >     • Couldn't match type: HM.HashMap k4 Value
datadog                   >                      with: Data.Aeson.KeyMap.KeyMap Value
datadog                   >       Expected: Object
datadog                   >         Actual: HM.HashMap k4 Value
datadog                   >     • In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON $ downtime ^. id') basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON $ downtime ^. id') basemap
datadog                   >       In an equation for ‘toJSON’:
datadog                   >           toJSON downtime
datadog                   >             = Object $ HM.insert "id" (toJSON $ downtime ^. id') basemap
datadog                   >             where
datadog                   >                 (Object basemap) = toJSON (downtime ^. spec)
datadog                   >     |
datadog                   > 147 |   toJSON downtime = Object $ HM.insert "id" (toJSON $ downtime ^. id') basemap
datadog                   >     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:147:72: error:
datadog                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
datadog                   >                      with: HM.HashMap k4 Value
datadog                   >       Expected: HM.HashMap k4 Value
datadog                   >         Actual: Object
datadog                   >     • In the third argument of ‘HM.insert’, namely ‘basemap’
datadog                   >       In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON $ downtime ^. id') basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON $ downtime ^. id') basemap
datadog                   >     |
datadog                   > 147 |   toJSON downtime = Object $ HM.insert "id" (toJSON $ downtime ^. id') basemap
datadog                   >     |                                                                        ^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:235:27: error:
datadog                   >     • Couldn't match type: HM.HashMap k3 Value
datadog                   >                      with: Data.Aeson.KeyMap.KeyMap Value
datadog                   >       Expected: Object
datadog                   >         Actual: HM.HashMap k3 Value
datadog                   >     • In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON (event ^. id')) basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON (event ^. id')) basemap
datadog                   >       In an equation for ‘toJSON’:
datadog                   >           toJSON event
datadog                   >             = Object $ HM.insert "id" (toJSON (event ^. id')) basemap
datadog                   >             where
datadog                   >                 (Object basemap) = toJSON (event ^. details)
datadog                   >     |
datadog                   > 235 |   toJSON event = Object $ HM.insert "id" (toJSON (event ^. id')) basemap
datadog                   >     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:235:66: error:
datadog                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
datadog                   >                      with: HM.HashMap k3 Value
datadog                   >       Expected: HM.HashMap k3 Value
datadog                   >         Actual: Object
datadog                   >     • In the third argument of ‘HM.insert’, namely ‘basemap’
datadog                   >       In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON (event ^. id')) basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON (event ^. id')) basemap
datadog                   >     |
datadog                   > 235 |   toJSON event = Object $ HM.insert "id" (toJSON (event ^. id')) basemap
datadog                   >     |                                                                  ^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:292:26: error:
datadog                   >     • Couldn't match type: HM.HashMap k2 Value
datadog                   >                      with: Data.Aeson.KeyMap.KeyMap Value
datadog                   >       Expected: Object
datadog                   >         Actual: HM.HashMap k2 Value
datadog                   >     • In the second argument of ‘($)’, namely
datadog                   >         ‘HM.fromList
datadog                   >            [("silenced", toJSON (opts ^. silenced)),
datadog                   >             ("notify_no_data", Bool (opts ^. notifyNoData)),
datadog                   >             ("no_data_timeframe", 
datadog                   >              maybe Null (Number . fromIntegral) (opts ^. noDataTimeframe)),
datadog                   >             ("timeout_h", 
datadog                   >              maybe Null (Number . fromIntegral) (opts ^. timeoutH)),
datadog                   >             ....]’
datadog                   >       In the expression:
datadog                   >         Object
datadog                   >           $ HM.fromList
datadog                   >               [("silenced", toJSON (opts ^. silenced)),
datadog                   >                ("notify_no_data", Bool (opts ^. notifyNoData)),
datadog                   >                ("no_data_timeframe", 
datadog                   >                 maybe Null (Number . fromIntegral) (opts ^. noDataTimeframe)),
datadog                   >                ("timeout_h", 
datadog                   >                 maybe Null (Number . fromIntegral) (opts ^. timeoutH)),
datadog                   >                ....]
datadog                   >       In an equation for ‘toJSON’:
datadog                   >           toJSON opts
datadog                   >             = Object
datadog                   >                 $ HM.fromList
datadog                   >                     [("silenced", toJSON (opts ^. silenced)),
datadog                   >                      ("notify_no_data", Bool (opts ^. notifyNoData)),
datadog                   >                      ("no_data_timeframe", 
datadog                   >                       maybe Null (Number . fromIntegral) (opts ^. noDataTimeframe)),
datadog                   >                      ....]
datadog                   >     |
datadog                   > 292 |   toJSON opts = Object $ HM.fromList [ ("silenced", toJSON (opts ^. silenced))
datadog                   >     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:314:24: error:
datadog                   >     • Couldn't match type: HM.HashMap k1 Value
datadog                   >                      with: Data.Aeson.KeyMap.KeyMap Value
datadog                   >       Expected: Object
datadog                   >         Actual: HM.HashMap k1 Value
datadog                   >     • In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "options" (toJSON (ms ^. options)) hmap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "options" (toJSON (ms ^. options)) hmap
datadog                   >       In an equation for ‘toJSON’:
datadog                   >           toJSON ms
datadog                   >             = Object $ HM.insert "options" (toJSON (ms ^. options)) hmap
datadog                   >             where
datadog                   >                 (Object hmap)
datadog                   >                   = object
datadog                   >                       $ prependMaybe ("name" .=) (ms ^. name)
datadog                   >                           $ prependMaybe
datadog                   >                               ("message" .=) (ms ^. message)
datadog                   >                               ["type" .= pack (show (ms ^. type')), ....]
datadog                   >     |
datadog                   > 314 |   toJSON ms = Object $ HM.insert "options" (toJSON (ms ^. options)) hmap
datadog                   >     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:314:69: error:
datadog                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
datadog                   >                      with: HM.HashMap k1 Value
datadog                   >       Expected: HM.HashMap k1 Value
datadog                   >         Actual: Object
datadog                   >     • In the third argument of ‘HM.insert’, namely ‘hmap’
datadog                   >       In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "options" (toJSON (ms ^. options)) hmap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "options" (toJSON (ms ^. options)) hmap
datadog                   >     |
datadog                   > 314 |   toJSON ms = Object $ HM.insert "options" (toJSON (ms ^. options)) hmap
datadog                   >     |                                                                     ^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:359:29: error:
datadog                   >     • Couldn't match type: HM.HashMap k0 Value
datadog                   >                      with: Data.Aeson.KeyMap.KeyMap Value
datadog                   >       Expected: Object
datadog                   >         Actual: HM.HashMap k0 Value
datadog                   >     • In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON (monitor ^. id')) basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON (monitor ^. id')) basemap
datadog                   >       In an equation for ‘toJSON’:
datadog                   >           toJSON monitor
datadog                   >             = Object $ HM.insert "id" (toJSON (monitor ^. id')) basemap
datadog                   >             where
datadog                   >                 (Object basemap) = toJSON (monitor ^. spec)
datadog                   >     |
datadog                   > 359 |   toJSON monitor = Object $ HM.insert "id" (toJSON (monitor ^. id')) basemap
datadog                   >     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
datadog                   >  
datadog                   > /tmp/stack-e8cbdd3b301cc36c/datadog-0.2.5.0/src/Network/Datadog/Internal.hs:359:70: error:
datadog                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
datadog                   >                      with: HM.HashMap k0 Value
datadog                   >       Expected: HM.HashMap k0 Value
datadog                   >         Actual: Object
datadog                   >     • In the third argument of ‘HM.insert’, namely ‘basemap’
datadog                   >       In the second argument of ‘($)’, namely
datadog                   >         ‘HM.insert "id" (toJSON (monitor ^. id')) basemap’
datadog                   >       In the expression:
datadog                   >         Object $ HM.insert "id" (toJSON (monitor ^. id')) basemap
datadog                   >     |
datadog                   > 359 |   toJSON monitor = Object $ HM.insert "id" (toJSON (monitor ^. id')) basemap
datadog                   >     |                                                                      ^^^^^^^
```

### PR DESCRIPTION
**Pull request by onslaughtq**
The default configuration has been bumped to LTS 18. A secondary LTS 18
yaml file was also added, that adds support for Aeson 2.

ADditionally, based on new tooling recommendations, the cabal file is
now checked in, and included as part of the repo.

Fixes #40

### CODE REVIEW

**Comment by ysangkok** [comment]
@iand675 Any comments on this? Looks good to me.

**Comment by ysangkok** [comment]
See also #42.

**Comment by onslaughtq** [comment]
Closing this since #42 was merged in
